# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-06 20:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=50)),
                ('first_name', models.CharField(max_length=50)),
                ('date_of_birth', models.DateField()),
                ('address1', models.CharField(max_length=50)),
                ('address2', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('zip_code', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=20)),
                ('school_email_address', models.CharField(max_length=100, unique=True)),
                ('personal_email_address', models.CharField(max_length=100, unique=True)),
                ('school_name', models.CharField(max_length=100)),
                ('school_address', models.CharField(max_length=100)),
                ('degree_level', models.CharField(choices=[('BA', 'Bachelor'), ('MA', 'Master'), ('DR', 'Doctor')], max_length=2)),
                ('graduation_year', models.IntegerField()),
                ('major', models.CharField(max_length=50)),
                ('second_major', models.CharField(max_length=50, null=True)),
                ('facebook_link', models.CharField(max_length=50)),
                ('linked_in_link', models.CharField(max_length=50, null=True)),
                ('acceptance_status', models.CharField(choices=[('BA', 'Bachelor'), ('MA', 'Master'), ('DR', 'Doctor')], default='PE', max_length=2)),
            ],
        ),
    ]
