# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-19 22:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='external_id',
            field=models.CharField(default='myDefault', max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='member',
            name='acceptance_status',
            field=models.CharField(choices=[('BA', "Bachelor's"), ('MA', "Master's"), ('DR', 'Doctoral')], default='PE', max_length=2),
        ),
        migrations.AlterField(
            model_name='member',
            name='degree_level',
            field=models.CharField(choices=[('BA', "Bachelor's"), ('MA', "Master's"), ('DR', 'Doctoral')], max_length=2),
        ),
    ]
