# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-23 22:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20170822_1753'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberUniversity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_email_address', models.CharField(max_length=100, unique=True)),
                ('degree_level', models.CharField(choices=[('BA', "Bachelor's"), ('MA', "Master's"), ('DR', 'Doctoral')], max_length=2)),
                ('graduation_year', models.IntegerField()),
                ('major', models.CharField(max_length=50)),
                ('second_major', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='member',
            name='degree_level',
        ),
        migrations.RemoveField(
            model_name='member',
            name='graduation_year',
        ),
        migrations.RemoveField(
            model_name='member',
            name='major',
        ),
        migrations.RemoveField(
            model_name='member',
            name='school_address',
        ),
        migrations.RemoveField(
            model_name='member',
            name='school_email_address',
        ),
        migrations.RemoveField(
            model_name='member',
            name='school_name',
        ),
        migrations.RemoveField(
            model_name='member',
            name='second_major',
        ),
        migrations.AlterField(
            model_name='member',
            name='acceptance_status',
            field=models.CharField(choices=[('PE', 'Pending'), ('AC', 'Accepted'), ('RE', 'Rejected'), ('HO', 'Holding')], default='PE', max_length=2),
        ),
        migrations.AddField(
            model_name='memberuniversity',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Member'),
        ),
        migrations.AddField(
            model_name='memberuniversity',
            name='university_assigned',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.University'),
        ),
    ]
