# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-23 22:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_member_university_assigned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='facebook_link',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='member',
            name='first_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='member',
            name='last_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='member',
            name='linked_in_link',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='personal_email_address',
            field=models.CharField(max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='zip_code',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='memberuniversity',
            name='major',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='memberuniversity',
            name='school_email_address',
            field=models.CharField(max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name='memberuniversity',
            name='second_major',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
