# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-26 16:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20170823_1759'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='school_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
