# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-07 13:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_member_school_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
